// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX_Su911r960swY__3QSwBZmMIc99wVdI',
    appId: '1:70991764761:web:1ae61b7deb3d5af4347988',
    messagingSenderId: '70991764761',
    projectId: 'bmi-65d88',
    authDomain: 'bmi-65d88.firebaseapp.com',
    storageBucket: 'bmi-65d88.firebasestorage.app',
    measurementId: 'G-P6VQZQ90MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjDbAb7DKvkuoAHuYYH-NfNsZg28h02dw',
    appId: '1:70991764761:android:d8e018dd95cd9bcb347988',
    messagingSenderId: '70991764761',
    projectId: 'bmi-65d88',
    storageBucket: 'bmi-65d88.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX_Su911r960swY__3QSwBZmMIc99wVdI',
    appId: '1:70991764761:web:6bed1e2d91ea5e9e347988',
    messagingSenderId: '70991764761',
    projectId: 'bmi-65d88',
    authDomain: 'bmi-65d88.firebaseapp.com',
    storageBucket: 'bmi-65d88.firebasestorage.app',
    measurementId: 'G-F8DM401LKM',
  );
}
